# NOTE THAT THIS IS AN EXAMPLE BOILERPLATE SCRIPT CREATED IN PIP PROJECT TEMPLATE PROJECT.
# PLEASE REMOVE OR UPDATE TO FIT YOUR PROJECT.

from ._DataContainer import DataContainer

__all__ = ["DataContainer"]
